require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SubdomainsController do

  # This should return the minimal set of attributes required to create a valid
  # Subdomain. As you add validations to Subdomain, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { :name => "validname" }
  end

  describe "GET index" do
    it "assigns all subdomains as @subdomains" do
      subdomain = Subdomain.create! valid_attributes
      get :index
      assigns(:subdomains).should eq([subdomain])
    end
  end

  describe "GET show" do
    it "assigns the requested subdomain as @subdomain" do
      subdomain = Subdomain.create! valid_attributes
      get :show, :id => subdomain.id.to_s
      assigns(:subdomain).should eq(subdomain)
    end
  end

  describe "GET new" do
    it "assigns a new subdomain as @subdomain" do
      get :new
      assigns(:subdomain).should be_a_new(Subdomain)
    end
  end

  describe "GET edit" do
    it "assigns the requested subdomain as @subdomain" do
      subdomain = Subdomain.create! valid_attributes
      get :edit, :id => subdomain.id.to_s
      assigns(:subdomain).should eq(subdomain)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Subdomain" do
        expect {
          post :create, :subdomain => valid_attributes
        }.to change(Subdomain, :count).by(1)
      end

      it "assigns a newly created subdomain as @subdomain" do
        post :create, :subdomain => valid_attributes
        assigns(:subdomain).should be_a(Subdomain)
        assigns(:subdomain).should be_persisted
      end

      it "redirects to the created subdomain" do
        post :create, :subdomain => valid_attributes
        response.should redirect_to(Subdomain.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved subdomain as @subdomain" do
        # Trigger the behavior that occurs when invalid params are submitted
        Subdomain.any_instance.stub(:save).and_return(false)
        post :create, :subdomain => {}
        assigns(:subdomain).should be_a_new(Subdomain)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Subdomain.any_instance.stub(:save).and_return(false)
        post :create, :subdomain => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested subdomain" do
        subdomain = Subdomain.create! valid_attributes
        # Assuming there are no other subdomains in the database, this
        # specifies that the Subdomain created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Subdomain.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => subdomain.id, :subdomain => {'these' => 'params'}
      end

      it "assigns the requested subdomain as @subdomain" do
        subdomain = Subdomain.create! valid_attributes
        put :update, :id => subdomain.id, :subdomain => valid_attributes
        assigns(:subdomain).should eq(subdomain)
      end

      it "redirects to the subdomain" do
        subdomain = Subdomain.create! valid_attributes
        put :update, :id => subdomain.id, :subdomain => valid_attributes
        response.should redirect_to(subdomain)
      end
    end

    describe "with invalid params" do
      it "assigns the subdomain as @subdomain" do
        subdomain = Subdomain.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Subdomain.any_instance.stub(:save).and_return(false)
        put :update, :id => subdomain.id.to_s, :subdomain => {}
        assigns(:subdomain).should eq(subdomain)
      end

      it "re-renders the 'edit' template" do
        subdomain = Subdomain.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Subdomain.any_instance.stub(:save).and_return(false)
        put :update, :id => subdomain.id.to_s, :subdomain => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested subdomain" do
      subdomain = Subdomain.create! valid_attributes
      expect {
        delete :destroy, :id => subdomain.id.to_s
      }.to change(Subdomain, :count).by(-1)
    end

    it "redirects to the subdomains list" do
      subdomain = Subdomain.create! valid_attributes
      delete :destroy, :id => subdomain.id.to_s
      response.should redirect_to(subdomains_url)
    end
  end

end

